// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhxftVwASz_lgs2nSll0RJc9dksDwJFo',
    appId: '1:546103321403:web:bd37da2357b847af864d1e',
    messagingSenderId: '546103321403',
    projectId: 'cvproject-1',
    authDomain: 'cvproject-1.firebaseapp.com',
    storageBucket: 'cvproject-1.appspot.com',
    measurementId: 'G-LR9E8D8CQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNki-QLF3NrRzBlhhjiPVss7J1NkhuX1g',
    appId: '1:546103321403:android:4ed46fda837ad192864d1e',
    messagingSenderId: '546103321403',
    projectId: 'cvproject-1',
    storageBucket: 'cvproject-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRb1z_Ppn1_9dJw9bnN67NBkqTuZct3s',
    appId: '1:546103321403:ios:a870bbfd85eaff05864d1e',
    messagingSenderId: '546103321403',
    projectId: 'cvproject-1',
    storageBucket: 'cvproject-1.appspot.com',
    iosBundleId: 'com.example.cvprojectFlutter',
  );
}
